import React from 'react'
import Link from 'gatsby-link'
import "./layout.css"

const InfoMars = () =>
    (
    <div>
    <h1>Mars</h1>

    <p>Mars is the fourth planet from the Sun and the second-smallest planet in the Solar System after Mercury. In English, Mars carries a name of the Roman god of war and is often referred to as the 'Red Planet'.1516 The latter refers to the effect of the iron oxide prevalent on Mars' surface, which gives it a reddish appearance distinctive among the astronomical bodies visible to the naked eye.17 Mars is a terrestrial planet with a thin atmosphere, having surface features reminiscent both of the impact craters of the Moon and the valleys, deserts, and polar ice caps of Earth.</p>

<p>The days and seasons are likewise comparable to those of Earth, because the rotational period as well as the tilt of the rotational axis relative to the ecliptic plane are very similar. Mars is the site of Olympus Mons, the largest volcano and highest known mountain in the Solar System, and of Valles Marineris, one of the largest canyons in the Solar System. The smooth Borealis basin in the northern hemisphere covers 40% of the planet and may be a giant impact feature.1819 Mars has two moons, Phobos and Deimos, which are small and irregularly shaped. These may be captured asteroids,2021 similar to 5261 Eureka, a Mars trojan.</p>

<p>There are ongoing investigations assessing the past habitability potential of Mars, as well as the possibility of extant life. Future astrobiology missions are planned, including the Mars 2020 and Rosalind Franklin rovers.22232425 Liquid water cannot exist on the surface of Mars due to low atmospheric pressure, which is less than 1% of the Earth's,26 except at the lowest elevations for short periods.2728 The two polar ice caps appear to be made largely of water.2930 The volume of water ice in the south polar ice cap, if melted, would be sufficient to cover the entire planetary surface to a depth of 11 meters (36 ft).31 In November 2016, NASA reported finding a large amount of underground ice in the Utopia Planitia region of Mars. The volume of water detected has been estimated to be equivalent to the volume of water in Lake Superior.</p>

<p>Mars can easily be seen from Earth with the naked eye, as can its reddish coloring. Its apparent magnitude reaches −2.94,11 which is surpassed only by Jupiter, Venus, the Moon, and the Sun. Optical ground-based telescopes are typically limited to resolving features about 300 kilometers (190 mi) across when Earth and Mars are closest because of Earth's atmosphere.</p>p


<h2>Physical characteristics</h2>

<p>Mars is approximately half the diameter of Earth, with a surface area only slightly less than the total area of Earth's dry land.9 Mars is less dense than Earth, having about 15% of Earth's volume and 11% of Earth's mass, resulting in about 38% of Earth's surface gravity. The red-orange appearance of the Martian surface is caused by iron(III) oxide, or rust.36 It can look like butterscotch;37 other common surface colors include golden, brown, tan, and greenish, depending on the minerals present.</p>

<h2>Internal structure</h2>

<p>Like Earth, Mars has differentiated into a dense metallic core overlaid by less dense materials.38 Current models of its interior imply a core with a radius of about 1,794 ± 65 kilometers (1,115 ± 40 mi), consisting primarily of iron and nickel with about 16–17% sulfur.39 This iron(II) sulfide core is thought to be twice as rich in lighter elements as Earth's.40 The core is surrounded by a silicate mantle that formed many of the tectonic and volcanic features on the planet, but it appears to be dormant. Besides silicon and oxygen, the most abundant elements in the Martian crust are iron, magnesium, aluminum, calcium, and potassium. The average thickness of the planet's crust is about 50 km (31 mi), with a maximum thickness of 125 km (78 mi).40 Earth's crust averages 40 km (25 mi).</p>

<h2>Surface geology</h2>


<p>Mars is a terrestrial planet that consists of minerals containing silicon and oxygen, metals, and other elements that typically make up rock. The surface of Mars is primarily composed of tholeiitic basalt,41 although parts are more silica-rich than typical basalt and may be similar to andesitic rocks on Earth or silica glass. Regions of low albedo suggest concentrations of plagioclase feldspar, with northern low albedo regions displaying higher than normal concentrations of sheet silicates and high-silicon glass. Parts of the southern highlands include detectable amounts of high-calcium pyroxenes. Localized concentrations of hematite and olivine have been found.42 Much of the surface is deeply covered by finely grained iron(III) oxide dust.</p>

<p>Although Mars has no evidence of a structured global magnetic field,46 observations show that parts of the planet's crust have been magnetized, suggesting that alternating polarity reversals of its dipole field have occurred in the past. This paleomagnetism of magnetically susceptible minerals is similar to the alternating bands found on Earth's ocean floors. One theory, published in 1999 and re-examined in October 2005 (with the help of the Mars Global Surveyor), is that these bands suggest plate tectonic activity on Mars four billion years ago, before the planetary dynamo ceased to function and the planet's magnetic field faded.</p>

<p>It is thought that, during the Solar System's formation, Mars was created as the result of a stochastic process of run-away accretion of material from the protoplanetary disk that orbited the Sun. Mars has many distinctive chemical features caused by its position in the Solar System. Elements with comparatively low boiling points, such as chlorine, phosphorus, and sulphur, are much more common on Mars than Earth; these elements were probably pushed outward by the young Sun's energetic solar wind.</p>

<p>After the formation of the planets, all were subjected to the so-called "Late Heavy Bombardment". About 60% of the surface of Mars shows a record of impacts from that era, whereas much of the remaining surface is probably underlain by immense impact basins caused by those events. There is evidence of an enormous impact basin in the northern hemisphere of Mars, spanning 10,600 by 8,500 km (6,600 by 5,300 mi), or roughly four times the size of the Moon's South Pole – Aitken basin, the largest impact basin yet discovered. This theory suggests that Mars was struck by a Pluto-sized body about four billion years ago. The event, thought to be the cause of the Martian hemispheric dichotomy, created the smooth Borealis basin that covers 40% of the planet.</p>



<p>The Phoenix lander returned data showing Martian soil to be slightly alkaline and containing elements such as magnesium, sodium, potassium and chlorine. These nutrients are found in soils on Earth, and they are necessary for growth of plants.59 Experiments performed by the lander showed that the Martian soil has a basic pH of 7.7, and contains 0.6% of the salt perchlorate.This is a very high concentration and makes the Martian soil toxic (see also Martian soil toxicity).</p>

<p>Streaks are common across Mars and new ones appear frequently on steep slopes of craters, troughs, and valleys. The streaks are dark at first and get lighter with age. The streaks can start in a tiny area, then spread out for hundreds of metres. They have been seen to follow the edges of boulders and other obstacles in their path. The commonly accepted theories include that they are dark underlying layers of soil revealed after avalanches of bright dust or dust devils.66 Several other explanations have been put forward, including those that involve water or even the growth of organisms.</p>

<h2>Hydrology</h2>


<p>Liquid water cannot exist on the surface of Mars due to low atmospheric pressure, which is less than 1% that of Earth's,26 except at the lowest elevations for short periods.2728 The two polar ice caps appear to be made largely of water.2930 The volume of water ice in the south polar ice cap, if melted, would be sufficient to cover the entire planetary surface to a depth of 11 meters (36 ft).31 A permafrost mantle stretches from the pole to latitudes of about 60°.29 Large quantities of ice are thought to be trapped within the thick cryosphere of Mars. Radar data from Mars Express and the Mars Reconnaissance Orbiter show large quantities of ice at both poles (July 2005)6970 and at middle latitudes (November 2008). The Phoenix lander directly sampled water ice in shallow Martian soil on July 31, 2008.</p>

<p>Landforms visible on Mars strongly suggest that liquid water has existed on the planet's surface. Huge linear swathes of scoured ground, known as outflow channels, cut across the surface in about 25 places. These are thought to be a record of erosion caused by the catastrophic release of water from subsurface aquifers, though some of these structures have been hypothesized to result from the action of glaciers or lava.7374 One of the larger examples, Ma'adim Vallis is 700 km (430 mi) long, much greater than the Grand Canyon, with a width of 20 km (12 mi) and a depth of 2 km (1.2 mi) in places. It is thought to have been carved by flowing water early in Mars's history.75 The youngest of these channels are thought to have formed as recently as only a few million years ago.76 Elsewhere, particularly on the oldest areas of the Martian surface, finer-scale, dendritic networks of valleys are spread across significant proportions of the landscape. Features of these valleys and their distribution strongly imply that they were carved by runoff resulting from precipitation in early Mars history. Subsurface water flow and groundwater sapping may play important subsidiary roles in some networks, but precipitation was probably the root cause of the incision in almost all cases.</p>

<p>Along crater and canyon walls, there are thousands of features that appear similar to terrestrial gullies. The gullies tend to be in the highlands of the southern hemisphere and to face the Equator; all are poleward of 30° latitude. A number of authors have suggested that their formation process involves liquid water, probably from melting ice,7879 although others have argued for formation mechanisms involving carbon dioxide frost or the movement of dry dust.8081 No partially degraded gullies have formed by weathering and no superimposed impact craters have been observed, indicating that these are young features, possibly still active.79 Other geological features, such as deltas and alluvial fans preserved in craters, are further evidence for warmer, wetter conditions at an interval or intervals in earlier Mars history.82 Such conditions necessarily require the widespread presence of crater lakes across a large proportion of the surface, for which there is independent mineralogical, sedimentological and geomorphological evidence.</p>

<p>Further evidence that liquid water once existed on the surface of Mars comes from the detection of specific minerals such as hematite and goethite, both of which sometimes form in the presence of water.86 In 2004, Opportunity detected the mineral jarosite. This forms only in the presence of acidic water, which demonstrates that water once existed on Mars.87 More recent evidence for liquid water comes from the finding of the mineral gypsum on the surface by NASA's Mars rover Opportunity in December 2011.8889 It is estimated that the amount of water in the upper mantle of Mars, represented by hydroxyl ions contained within the minerals of Mars's geology, is equal to or greater than that of Earth at 50–300 parts per million of water, which is enough to cover the entire planet to a depth of 200–1,000 m (660–3,280 ft).</p>

<p>In 2005, radar data revealed the presence of large quantities of water ice at the poles69 and at mid-latitudes.The Mars rover Spirit sampled chemical compounds containing water molecules in March 2007. The Phoenix lander directly sampled water ice in shallow Martian soil on July 31, 2008.</p>

<p>On March 18, 2013, NASA reported evidence from instruments on the Curiosity rover of mineral hydration, likely hydrated calcium sulfate, in several rock samples including the broken fragments of "Tintina" rock and "Sutton Inlier" rock as well as in veins and nodules in other rocks like "Knorr" rock and "Wernicke" rock.929394 Analysis using the rover's DAN instrument provided evidence of subsurface water, amounting to as much as 4% water content, down to a depth of 60 cm (24 in), during the rover's traverse from the Bradbury Landing site to the Yellowknife Bay area in the Glenelg terrain.92 In September 2015, NASA announced that they had found conclusive evidence of hydrated brine flows on recurring slope lineae, based on spectrometer readings of the darkened areas of slopes.959697 These observations provided confirmation of earlier hypotheses based on timing of formation and their rate of growth, that these dark streaks resulted from water flowing in the very shallow subsurface.98 The streaks contain hydrated salts, perchlorates, which have water molecules in their crystal structure.99 The streaks flow downhill in Martian summer
    , when the temperature is above −23 degrees Celsius, and freeze at lower temperatures.</p>


<h2>Polar caps</h2>

<p>Mars has two permanent polar ice caps. During a pole's winter, it lies in continuous darkness, chilling the surface and causing the deposition of 25–30% of the atmosphere into slabs of CO2 ice (dry ice).106 When the poles are again exposed to sunlight, the frozen CO2 sublimes. These seasonal actions transport large amounts of dust and water vapor, giving rise to Earth-like frost and large cirrus clouds. Clouds of water-ice were photographed by the Opportunity rover in 2004.</p>

<p>The caps at both poles consist primarily (70%) of water ice. Frozen carbon dioxide accumulates as a comparatively thin layer about one metre thick on the north cap in the northern winter only, whereas the south cap has a permanent dry ice cover about eight metres thick. This permanent dry ice cover at the south pole is peppered by flat floored, shallow, roughly circular pits, which repeat imaging shows are expanding by meters per year; this suggests that the permanent CO2 cover over the south pole water ice is degrading over time.108 The northern polar cap has a diameter of about 1,000 km (620 mi) during the northern Mars summer,109 and contains about 1.6 million cubic kilometres (380,000 cu mi) of ice, which, if spread evenly on the cap, would be 2 km (1.2 mi) thick.110 (This compares to a volume of 2.85 million cubic kilometres (680,000 cu mi) for the Greenland ice sheet.) The southern polar cap has a diameter of 350 km (220 mi) and a thickness of 3 km (1.9 mi).111 The total volume of ice in the south polar cap plus the adjacent layered deposits has been estimated at 1.6 million cubic km.112 Both polar caps show spiral troughs, which recent analysis of SHARAD ice penetrating radar has shown are a result of katabatic winds that spiral due to the Coriolis Effect.</p>

<p>The seasonal frosting of areas near the southern ice cap results in the formation of transparent 1-metre-thick slabs of dry ice above the ground. With the arrival of spring, sunlight warms the subsurface and pressure from subliming CO2 builds up under a slab, elevating and ultimately rupturing it. This leads to geyser-like eruptions of CO2 gas mixed with dark basaltic sand or dust. This process is rapid, observed happening in the space of a few days, weeks or months, a rate of change rather unusual in geology – especially for Mars. The gas rushing underneath a slab to the site of a geyser carves a spiderweb-like pattern of radial channels under the ice, the process being the inverted equivalent of an erosion network formed by water draining through a single plughole.</p>

<h2>Geography and naming of surface features</h2>

<p>A MOLA-based topographic map showing highlands (red and orange) dominating the southern hemisphere of Mars, lowlands (blue) the northern. Volcanic plateaus delimit regions of the northern plains, whereas the highlands are punctuated by several large impact basins.
    These new impact craters on Mars occurred sometime between 2008 and 2014, as detected from orbit</p>

<p>Although better remembered for mapping the Moon, Johann Heinrich Mädler and Wilhelm Beer were the first "areographers". They began by establishing that most of Mars's surface features were permanent and by more precisely determining the planet's rotation period. In 1840, Mädler combined ten years of observations and drew the first map of Mars. Rather than giving names to the various markings, Beer and Mädler simply designated them with letters; Meridian Bay (Sinus Meridiani) was thus feature "a".</p>

<p>Today, features on Mars are named from a variety of sources. Albedo features are named for classical mythology. Craters larger than 60 km are named for deceased scientists and writers and others who have contributed to the study of Mars. Craters smaller than 60 km are named for towns and villages of the world with populations of less than 100,000. Large valleys are named for the word "Mars" or "star" in various languages; small valleys are named for rivers.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p>Large albedo features retain many of the older names, but are often updated to reflect new knowledge of the nature of the features. For example, Nix Olympica (the snows of Olympus) has become Olympus Mons (Mount Olympus).121 The surface of Mars as seen from Earth is divided into two kinds of areas, with differing albedo. The paler plains covered with dust and sand rich in reddish iron oxides were once thought of as Martian "continents" and given names like Arabia Terra (land of Arabia) or Amazonis Planitia (Amazonian plain). The dark features were thought to be seas, hence their names Mare Erythraeum, Mare Sirenum and Aurorae Sinus. The largest dark feature seen from Earth is Syrtis Major Planum.122 The permanent northern polar ice cap is named Planum Boreum, whereas the southern cap is called Planum Australe.</p>

<p>Mars's equator is defined by its rotation, but the location of its Prime Meridian was specified, as was Earth's (at Greenwich), by choice of an arbitrary point; Mädler and Beer selected a line for their first maps of Mars in 1830. After the spacecraft Mariner 9 provided extensive imagery of Mars in 1972, a small crater (later called Airy-0), located in the Sinus Meridiani ("Middle Bay" or "Meridian Bay"), was chosen for the definition of 0.0° longitude to coincide with the original selection.</p>

<p>Because Mars has no oceans and hence no "sea level", a zero-elevation surface had to be selected as a reference level; this is called the areoid124 of Mars, analogous to the terrestrial geoid. Zero altitude was defined by the height at which there is 610.5 Pa (6.105 mbar) of atmospheric pressure. This pressure corresponds to the triple point of water, and it is about 0.6% of the sea level surface pressure on Earth (0.006 atm).126 In practice, today this surface is defined directly from satellite gravity measurements. </p>




<Link to="/moon"> Go back to the homepage </Link>

<a href="https://en.wikipedia.org/wiki/Mars">source Wikipedia</a>
</div>
);



export default InfoMars